---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/default/requirements.yml

lint: |
  set -e
  yamllint . --strict
  ansible-lint

driver:
  name: docker

platforms:
  - name: ansible-jitsi-focal
    image: docker.io/borisskert/python3:focal
    pull: true
    pre_build_image: true
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    groups:
      - docker
#  - name: ansible-jitsi-buster
#    image: docker.io/borisskert/python3:buster
#    pull: true
#    pre_build_image: true
#    volumes:
#      - '/var/run/docker.sock:/var/run/docker.sock'
#    groups:
#      - docker
#      - debian

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../all-parameters/converge.yml
    verify: ../all-parameters/verify.yml
  inventory:
    group_vars:
      docker:
        molecule_docker_environment: true
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
