---
- name: create dockercompose directory
  file:
    path: "{{docker_compose.path}}"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: Copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: "{{docker_compose.path}}/{{docker_compose.filename}}"
    owner: root
    group: root
    mode: '0664'
  register: docker_compose_file
