---
- name: create dockercompose directory
  file:
    path: "{{docker_compose.path}}"
    state: directory
    owner: root
    group: root
    mode: '0775'

- name: template docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: "{{docker_compose.path}}/{{docker_compose.filename}}"
    owner: root
    group: root
    mode: '0644'
  register: docker_compose_file
