---
- include: check-parameters.yml
- include: create_compose_file.yml
- include: template-env-config.yml
- include: create-volume-directories.yml
- include: register-users.yml

- name: Create systemd unit file
  template:
    src: systemd.unitfile.j2
    dest: "/etc/systemd/system/{{service_name}}.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_unitfile

- name: Reload systemd
  command: systemctl daemon-reload
  when: systemd_unitfile.changed

- name: Restart service (by config change)
  service:
    name: "{{service_name}}"
    state: restarted
    enabled: yes
  when: docker_compose_file.changed or env_file.changed or systemd_unitfile.changed or account_files.changed

- name: Start service (if it's not already started)
  service:
    name: "{{service_name}}"
    state: started
