---
- include: check-parameters.yml
- include: create-compose-file.yml
- include: template-env-config.yml
- include: create-volume-directories.yml
- include: register-users.yml
- include: pull-docker-images.yml
- include: setup-systemd-service.yml

- name: Reload/restart jitsi meet service immediately
  meta: flush_handlers

- name: Enable/start jitsi meet service (if not started)
  service:
    name: "{{ service_name }}"
    enabled: true
    state: started
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
