---
- include: check-parameters.yml
- include: create_compose_file.yml
- include: template-env-config.yml
- include: create-volume-directories.yml
- include: register-users.yml
- include: pull-docker-images.yml
- include: setup-systemd-service.yml
