---
- name: Create systemd unit file
  template:
    src: systemd.unitfile.j2
    dest: "/etc/systemd/system/{{ service_name }}.service"
    owner: root
    group: root
    mode: 0644
  register: systemd_unitfile
  notify:
    - Reload systemd
    - Restart jitsi meet service

- name: Enable jitsi meet service
  service:
    name: "{{ service_name }}"
    enabled: true
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )

- name: Start jitsi meet service
  service:
    name: "{{ service_name }}"
    state: started
  register: jitsi_service_start
  when: not (
    molecule_docker_environment is defined
    and molecule_docker_environment | bool
    )
