---
- name: Copy gen_password.sh script
  copy:
    src: files/gen_passwords.sh
    dest: "{{ jitsi_docker_compose_working_directory }}/gen_passwords.sh"
    owner: root
    group: root
    mode: 0755
  register: gen_passwords_script

- name: create env template
  template:
    src: ./.env.j2
    dest: "{{ jitsi_docker_compose_working_directory }}/.env-template"
    owner: root
    group: root
    mode: 0640
  register: env_template

- name: Check if env file exists
  stat:
    path: "{{ jitsi_docker_compose_working_directory }}/.env"
  register: env_file_result

- name: create env file  # noqa 503
  copy:
    src: "{{ jitsi_docker_compose_working_directory }}/.env-template"
    remote_src: true
    dest: "{{ jitsi_docker_compose_working_directory }}/.env"
    owner: root
    group: root
    mode: 0640
  register: env_file
  when: not env_file_result.stat.exists or env_template.changed
  notify: Restart jitsi meet service

- name: Generate passwords  # noqa 503
  command: "{{ jitsi_docker_compose_working_directory }}/gen_passwords.sh"
  args:
    chdir: "{{ jitsi_docker_compose_working_directory }}/"
  when: env_file.changed or gen_passwords_script.changed
  register: gen_passwords
