---
- name: Converge
  hosts: all
  become: true

  roles:
    - role: ansible-meet-jitsi
      jitsi_volume: /srv/docker/jitsi
      jitsi_images_version: stable-5142-3
      jitsi_web_port: 10080
      jitsi_https_port: 10443
      jitsi_web_interface: 0.0.0.0
      jitsi_videobridge_interface: 0.0.0.0
      jitsi_external_url: http://localhost:10080
      jitsi_enable_auth: true
      jitsi_allow_guests: true
      jitsi_users:
        - username: myuser
          password: mypassword
        - username: myuser2
          password: mypassword2
      jitsi_force_recreate: false
