---
dependency:
  name: galaxy
  options:
    role-file: ./molecule/default/requirements.yml

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: ansible-jitsi-xenial
    box: ubuntu/xenial64
    memory: 1024
    cpus: 2
    instance_raw_config_args:
      - 'vm.network "private_network", ip: "192.168.33.87"'

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../all-parameters/converge.yml
    verify: ../all-parameters/verify.yml
  inventory:
    group_vars:
      debian:
        ansible_python_interpreter: /usr/bin/python3

verifier:
  name: ansible
